language: generic
branches:
  only:
    - develop
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2
services:
  - docker
env:
  global:
    - DOCKER_REGISTRY=openshift-registry.adorsys.de
    - IMAGE=${DOCKER_REGISTRY}/aspsp-registry-manager-dev/aspsp-registry-manager
    - OPENSHIFT_SERVER=https://openshift.adorsys.de
    - OC_VERSION=v3.11.0
    - OC_VERSION_COMMIT=0cbc58b
    - HELM_VERSION=v2.12.2
script:
  - mvn install -B -Dbuild.number=${TRAVIS_BUILD_NUMBER}
  - docker build -t $IMAGE .
deploy:
  - provider: script
    skip_cleanup: true
    script: bash devops/scripts/deploy.sh
    on:
      branch: develop
