version: "3"

networks:
  registry-manager-net:

volumes:
  aspsp-registry-manager-data:

services:
#  registry-manager-app:
#    image: registry-manager-app
#    build:
#      context: registry-manager-app
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - "8089:8089"
#    networks:
#      - registry-manager-net
#    environment:
#      - JAVA_TOOL_OPTIONS="-Xmx1024m"
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://aspsp-registry-postgres/aspsp_registry
#      - SPRING_DATASOURCE_USERNAME=manager
#      - SPRING_DATASOURCE_PASSWORD=manager
#    expose:
#      - 8089
#    depends_on:
#      - aspsp-registry-postgres

  aspsp-registry-postgres:
    image: centos/postgresql-95-centos7
    volumes:
      - aspsp-registry-manager-data:/var/lib/pgsql/data
      - ./registry-manager-db-impl/util/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - registry-manager-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=aspsp_registry
      - POSTGRESQL_USER=manager
      - POSTGRESQL_PASSWORD=manager
    expose:
      - 5432
