apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Chart.Name }}-app
spec:
  selector:
    app: {{ .Chart.Name }}-app
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Chart.Name }}-db/{{ .Values.db.name }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /opt/aspsp-registry-manager/config
      volumes:
        - name: config-volume
          secret:
            secretName: config-secret
