apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}-app
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Chart.Name }}-app
