spring:
  application.name: aspsp-registry-manager
  main:
    allow-bean-definition-overriding: true

info:
  app:
    name: ${spring.application.name}
    description: "Description"
    version: @project.version@
    artifactId: @project.artifactId@

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000

---
spring:
  profiles: default
