spring:
  application.name: aspsp-registry-manager
  main:
    allow-bean-definition-overriding: true

info:
  app:
    name: ${spring.application.name}
    description: '@project.description@'
    version: @project.version@
    build: '#@build.number@'
    artifactId: @project.artifactId@

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000

manager:
  users:
    - name: user1
      password: user
      role: READER
    - name: user2
      password: user
      role: MANAGER
    - name: user3
      password: user
      role: DEPLOYER

---
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost/aspsp_registry
    username: manager
    password: manager
  jpa:
    # TODO replace it with DB migration tool (like Flyway or Liquibase)
    hibernate:
      ddl-auto: update
    # Workaround to avoid this issue:
    # https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646
    # https://stackoverflow.com/a/52545424
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

logging.level.de.adorsys.registry.manager.client.AspspOutboundClient: DEBUG

xs2a-adapter:
  url: http://localhost:8999
