spring:
  application.name: aspsp-registry-manager
  main:
    allow-bean-definition-overriding: true

info:
  app:
    name: ${spring.application.name}
    description: "Description"
    version: @project.version@
    artifactId: @project.artifactId@

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000

---
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost/aspsp-registry
    username: manager
    password: manager
  # Workaround to avoid this issue:
  # https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646
  # https://stackoverflow.com/a/52545424
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
